export const locations = {
  main: '/',
  blog: '/blog',
  articleItem: '/blog:id',
  login: '/login',
  signUp: '/signup',
  ads: '/ads',
  adItemFull: '/ads:id',
  results: '/results',
  videoMain: '/videos',
  vimeoVideos: '/vimeovideos',
  maps: '/maps',
  aboutUs: '/about',
  images: '/images',
  news: '/news',
  academics: '/academics',
  shopping: '/ecommerce',
  cart: '/ecommerce/cart',
}
